# Generated by Django 3.0.4 on 2020-03-28 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sm_hr', '0003_auto_20200328_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sm_hr.Company')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sm_hr.Department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sm_hr.Designation')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sm_hr.EmployeePersonalInformation')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sm_hr.Section')),
            ],
        ),
    ]
