# Generated by Django 3.0.4 on 2020-03-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm_hr', '0005_attendence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendence',
            options={'base_manager_name': 'objects'},
        ),
    ]
