# Generated by Django 3.0.4 on 2020-04-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm_hr', '0006_auto_20200328_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendence',
            new_name='Attendance',
        ),
    ]
